version: '3.5'

services:
  apache:
    image: 'bitnami/apache:latest'
    user: "0:0"
    ports:
      - '80:80'
      - '443:443'
    networks:
      - dest-net
    volumes:
      - ./config/apache/httpd.conf:/opt/bitnami/apache/conf/httpd.conf:ro
      - ./config/apache/r-ssl.conf:/vhosts/my_vhost.conf:ro
      - ./config/ssl:/etc/ssl:ro
    environment:
      - APACHE_HTTP_PORT_NUMBER=80
      - APACHE_HTTPS_PORT_NUMBER=443

  shiny:
    image: 'rocker/shiny'
    volumes:
      - /srv/shinyapps:/srv/shiny-server
    networks:
      - dest-net

  rstudio:
    image: 'rocker/rstudio'
    networks:
      - dest-net
    environment:
      - PASSWORD=rinproduction
      - DISABLE_AUTH=false
      # - ADD=shiny

  
networks:
  dest-net:
    name: rweb_dest-net
  
